### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Crpto999** [nocpiun/ferrum#2]
两个需求：
文件或者文件夹 为什么不能打击打开呢  
图片文件夹如果能以图片墙瀑布流的形式自动预览展示会很实用

**Comment by NriotHrreion** [comment]
这个功能已经做好了，Ferrum 2.0发布之后就可以用了
![image](https://github.com/user-attachments/assets/0576ed27-1dec-4320-9f13-c4f2af839a9a)
